a = int(input())
b = int(input())
#arithmetic operators
print("Addition",a+b)
print("Sub",a-b)
print("Mul",a*b)
print("Div",a/b)
print("Mod",a%b)
print("Exp",a**b)
print("Floor division",a//b)